# -*- coding: utf-8 -*-
"""Break the Great Guilds' bounty rules one at a time and prove a harness notices.

Modelled on tools/mutate_iron_court.py, with two differences that matter:
- THE GUILDS HARNESSES FAIL BY assert, not by printing FAIL. A mutant is caught when a
  harness exits non-zero with a traceback naming a harness file; a crash naming the
  model file (a parse error) is an ERROR, not a catch.
- FILES ARE READ AND WRITTEN AS BYTES. The model is LF and the UI is CRLF; a text-mode
  round trip would rewrite one of them.

The mutation goes into the SHIPPED Lua and is restored in a `finally`. Neither harness
writes a file, so unlike the Iron Court run there is nothing generated to restore.

    py tools/mutate_guilds.py            # every mutant
    py tools/mutate_guilds.py --selftest
"""
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MOD = os.path.join(ROOT, "Modding Files", "pack", "script", "campaign", "mod")
M = os.path.join(MOD, "zzz_derpy_guilds.lua")
U = os.path.join(MOD, "zzz_derpy_guilds_ui.lua")   # CRLF: a two-line anchor needs \r\n
A = os.path.join(MOD, "zzz_derpy_guilds_ai.lua")   # CRLF too
LUA = r"C:\Program Files (x86)\Lua\5.1\lua.exe"
HARNESSES = [os.path.join(ROOT, "tools", "_guilds_harness.lua"),
             os.path.join(ROOT, "tools", "_guilds_bounty_harness.lua")]

# (what it breaks, file, code as it ships, the mistake). Anchors are CODE lines.
MUTANTS = [
    ("the badge counting an offer the player cannot stake", U,
     b"        if o and not o.taken and GG.stake_affordable(faction, o) then",
     b"        if o and not o.taken then"),
    ("an untaken harry offer kept after its lord lost his army", M,
     b"            if k.shape and k.target == \"lord\" and not c:has_military_force() then",
     b"            if false then"),
    ("a building job in a settlement too small for it", M,
     b"                    if not okl or type(lvl) ~= \"number\" or lvl >= (need or 0) then",
     b"                    if true then"),
    ("a building job kept after the lower level is lost", M,
     b"        return row == nil or GG.upgrade_open(faction, row[3] or {}, row[4])",
     b"        return true"),
    ("the greyed opener's hover still saying click to open", U,
     b"GGUI.loc(GGUI.player_turn() and \"opener_click\" or \"opener_wait\")",
     b"GGUI.loc(\"opener_click\")"),
    ("a Leaderboard row's tooltip given the guild's whole description back", U,
     b"            local tip = GGUI.table_lines(L.guild, faction)\r\n",
     b"            local tip = GGUI.table_lines(L.guild, faction) .. \"||\""
     b" .. GGUI.loc_guild_desc(L.guild)\r\n"),
    ("the opener left grey when placement bails at turn start", U,
     b"    -- stay grey for the whole turn.\r\n    GGUI.gate_opener(GGUI.player_turn())",
     b"    -- stay grey for the whole turn."),
    ("the opener clickable during the AI round", U,
     b"        if not GGUI.player_turn() then return end\r\n        if GGUI.PICK then",
     b"        if GGUI.PICK then"),
    ("the opener not greyed at the player's turn end", U,
     b"        GGUI.gate_opener(false)\r\n    end, true)",
     b"    end, true)"),
    ("a research job for a tech the player cannot start", M,
     b"                if got >= need then found[#found + 1] = list[i] end",
     b"                found[#found + 1] = list[i]"),
    ("a building job for a level the player cannot upgrade to", M,
     b"                if r:building_exists(froms[j]) then",
     b"                if true then"),
    ("required_parents read as all parents", M,
     b"                if got >= need then found[#found + 1] = list[i] end",
     b"                if got >= #ps then found[#found + 1] = list[i] end"),
    ("the front line allowed for military work", M,
     b"        local front = (ai or not k.front_ok) and GG.front_regions(faction) or {}",
     b"        local front = {}"),
    ("a lord on the front posted", M,
     b"                                or keep(GG.char_on_front(faction, gen))) then",
     b"                                or true) then"),
    ("a pact partner made a target", M,
     b"        if pf:non_aggression_pact_with(e) then return false end",
     b""),
    ("the stake not spent", M,
     b"    if stake > 0 and not GG.spend(faction, o.guild, stake) then return false end",
     b""),
    ("the refund paid as a grant", M,
     b"    if g then g.fav = g.fav + amount end",
     b"    if g then GG.grant(faction, guild, amount, \"refund\") return end"),
    ("the new-war premium dropped", M,
     b"    if war == 1 then gm, rm = GG.BOUNTY_WAR_GOLD, GG.BOUNTY_WAR_REP end",
     b""),
    ("an opportune failure counted", M,
     b"    if not won or target == nil then return nil end",
     b"    if target == nil then return nil end"),
    ("any target counted", M,
     b"        if o.taken and not o.void and k and k.shape and o.target == tostring(target)",
     b"        if o.taken and not o.void and k and k.shape"),
    ("the void flag ignored on cancel", M,
     b"    if o and o.void then GG.refund(faction, o.guild, o.stake) end",
     b""),
    ("a hero bounty completed on every success", M,
     b"            if o.done == (o.amount or 1) then",
     b"            if true then"),
    ("the progress saved after the completion call", M,
     b"            o.done = (o.done or 0) + 1\n            GG.save_bounties(faction)",
     b"            o.done = (o.done or 0) + 1"),
    ("a researched tech still offered", M,
     b"            if not used[key] and not has(key) then",
     b"            if not used[key] then"),
    # RIVALS TAKE BOUNTIES (2026-09-29).
    ("a rival's pool widened past its wars", M,
     b"        local pool = GG.bounty_pool(faction, war == true and not ai, ai)",
     b"        local pool = GG.bounty_pool(faction, war == true or ai == true, ai)"),
    ("humans never a rival's target", M,
     b"        if e:is_dead() or (e:is_human() and not human_ok) or e:name() == pf:name() then",
     b"        if e:is_dead() or e:is_human() or e:name() == pf:name() then"),
    ("two rivals on one target", A,
     b"                                GGAI.by_target, true)",
     b"                                {}, true)"),
    ("a rival's stake not spent", A,
     b"        if o and GG.spend(faction, guild, o.stake or 0) then",
     b"        if o then"),
    ("a rival's failure not charged", A,
     b"        GG.penalise(faction, o.guild, GG.bounty_fail_cost(o, faction))",
     b"        local _ = 0"),
    ("a void that also penalises", A,
     b"        GGAI.tell(faction, o, \"hunt_void\")",
     b"        GG.penalise(faction, o.guild, 999) GGAI.tell(faction, o, \"hunt_void\")"),
    ("an unreadable read that pays", A,
     b"    local ok, yes = pcall(test, faction, o)",
     b"    local ok, yes = pcall(test, faction, o) if not ok then return true end"),
    ("the feed call made for a non-human target", A,
     b"    if not owner or owner == \"\" or not GG.is_human(owner) then return end",
     b"    if not owner or owner == \"\" then return end"),
    ("a bounty done on its last turn failed instead", A,
     b"    if GGAI.is_done(faction, o) then",
     b"    if GGAI.is_done(faction, o) and turn - (o.posted or turn) < GG.BOUNTY_TURN_LIMIT then"),
    ("a sack of any town counted", A,
     b"    if not o or o.kind ~= \"region_sack\" or o.target ~= region then return false end",
     b"    if not o or o.kind ~= \"region_sack\" then return false end"),
    ("a second bounty taken while one is held", A,
     b"        elseif not GGAI.bounty[f] then",
     b"        else"),
    # FINAL REVIEW (2026-09-29): a rival works its own front, and only what it can pay for.
    ("a rival's region or lord across the map", M,
     b"        local function keep(on) if ai then return on end return not on end",
     b"        local function keep(on) if ai then return true end return not on end"),
    ("a rival's hero across the map", M,
     b"                           and (not ai or GG.char_on_front(faction, c)) then",
     b"                           then"),
    ("a rival taking hero work that needs two hits", A,
     b"GGAI.SKIP_KINDS = {job_captives = true, hero_harry = true, hero_sabotage = true}",
     b"GGAI.SKIP_KINDS = {job_captives = true}"),
    ("a broke rival walking the map", A,
     b"    if (fav or 0) < GG.bounty_stake(GG.bounty_pay()) then return nil end",
     b""),
    ("the round's count never written", A,
     b"    if settled + n.taken > 0 then",
     b"    if false then"),
    ("the AI round never runs the bounty pass", A,
     b"    local okb, err = pcall(GGAI.bounty_sweep, names, turn)",
     b"    local okb, err = true, nil"),
    # SERVICE POOLS (2026-09-29).
    ("a service off the cards still sold", M,
     b"    if not GG.on_card(faction, service_key) then return false, \"card\" end",
     b""),
    ("a draw that repeats the card's last service", M,
     b"                    if pool[j].key ~= old[i] then fresh[#fresh + 1] = pool[j] end",
     b"                    fresh[#fresh + 1] = pool[j]"),
    ("a redraw every turn instead of every period", M,
     b"    if c and c.turn and math.floor(turn / n) <= math.floor(c.turn / n) then return false end",
     b"    if c and c.turn == turn then return false end"),
    ("hostile services drawn with the switch off", M,
     b"       and GG.setting(\"hostile_services\") == false then\n        return false\n    end\n    return GG.needs_ok(faction, s)",
     b"       and false then\n        return false\n    end\n    return GG.needs_ok(faction, s)"),
    ("a friendly service aimed at an enemy army", M,
     b"            if c:faction():name() ~= faction then return false end",
     b""),
    ("an enemy settlement service on a friend", M,
     b"then return owner:name() == faction end\n            return cm:get_faction(faction):at_war_with(owner)",
     b"then return owner:name() == faction end\n            return true"),
    ("a sale to the wrong target", M,
     b"    if GG.needs_target(s) and not GG.target_ok(faction, s, target) then return false, \"target\" end",
     b"    if GG.needs_target(s) and not target then return false, \"target\" end"),
    ("an army bundle on the character cqi", M,
     b"                                            force:command_queue_index(), s.turns)",
     b"                                            target, s.turns)"),
    ("the rivals' round buying from last period's cards", A,
     b"                GG.rotate_cards(name, turn)",
     b"                local _ = turn"),
    ("the rotation announced to rivals", M,
     b"    if not GG.is_human(faction) then return end\n    GG.log_add(faction, \"rotation\"",
     b"    GG.log_add(faction, \"rotation\""),
    # SERVICE POOLS, the final review's survivors (2026-09-29).
    ("saved cards loaded as the slot defaults", M,
     b"        keys[i] = (svc and svc.guild == g and svc.rank == rank) and k",
     b"        keys[i] = false and k"),
    ("a reload that forgets the drawn cards", M,
     b"    -- may still hold cards.\n    GG.load_cards(faction)\n",
     b"    -- may still hold cards.\n"),
    ("rotate_turns read under Custom only", M,
     b"            if type(GG.TUNE_DEFAULTS[key]) == \"boolean\" or GG.EVERY_PRESET[key] then",
     b"            if type(GG.TUNE_DEFAULTS[key]) == \"boolean\" then"),
    ("rivals aim a settlement service at an enemy", A,
     b"    if s.kind == \"settlement\" then return GGAI.pick_own_region(faction) end",
     b"    if s.kind == \"settlement\" then return GGAI.pick_enemy_region(faction) end"),
    ("every faction in the world draws cards", M,
     b"    if not GG.covered(faction) then return false end\n    local c = GG.cards[faction]",
     b"    local c = GG.cards[faction]"),
    ("a rival's strike on a human's settlement unannounced", A,
     b"    if s.kind ~= \"enemy_settlement\" then return nil end",
     b"    do return nil end"),
    # PAID FOR AND NOTHING DELIVERED (2026-09-29).
    ("a regiment sold for a full army", M,
     b"            return mf:unit_count_limit() - mf:unit_list():num_items() > 0",
     b"            return true"),
    ("the room check applied to every army service", M,
     b"            if s.kind ~= \"unit\" and not s.room then return true end",
     b"            if s.kind == \"ranks\" then return true end"),
    ("ranks sold for a character at the top", M,
     b"                return top == nil or c:rank() < top",
     b"                return true"),
    ("an unknown top rank refusing everyone", M,
     b"                return top == nil or c:rank() < top",
     b"                return top ~= nil and c:rank() < top"),
    ("a payload that throws escaping GG.buy", M,
     b"    local okp, err = pcall(GG.payload, faction, s, target)",
     b"    local okp, err = true, GG.payload(faction, s, target)"),
    ("a failed payload keeping the favour", M,
     b"    if f and f[s.guild] then f[s.guild].fav = f[s.guild].fav + price end",
     b"    if false then end"),
    ("a failed payload keeping the cooldown", M,
     b"    if GG.cooldowns[faction] then GG.cooldowns[faction][s.key] = nil end",
     b"    if false then end"),
    ("a refund held only in memory", M,
     b"    GG.log_add(faction, \"refund\", s.guild, s.key, price)\n    GG.save(faction)",
     b"    GG.log_add(faction, \"refund\", s.guild, s.key, price)"),
    ("the rivals picking the first army whatever it holds", A,
     b"           and (s == nil or GG.target_ok(faction, s, list[i].cqi)) then",
     b"           then"),
    ("the Hire hint not asking for room", U,
     b"    if s.kind == \"unit\" then return \"needs_army_room\" end",
     b"    if s.kind == \"unit\" then return \"needs_army\" end"),
    ("a refund not under the Yours filter", U,
     b"    mine   = {buy = true, refund = true, rank = true,",
     b"    mine   = {buy = true, rank = true,"),
    # THE STAGE 1 GAPS AND DEFERRED ISSUES (2026-09-29).
    ("a hostile service sold on a faction at peace", M,
     b"            return cm:get_faction(faction):at_war_with(victim)",
     b"            return true"),
    ("the map reveal sold on the buyer's own region", M,
     b"            return not owner or owner:is_null_interface() or owner:name() ~= faction",
     b"            return true"),
    ("the hostile pick taking a friend", U,
     b"        if f and GG.target_ok(faction, s, f) then return f end",
     b"        if f then return f end"),
    ("the reveal pick taking the buyer's own town", U,
     b"        local r = GGUI.selected_region()\r\n        if r and GG.target_ok(faction, s, r) then return r end\r\n        return nil\r\n    end\r\n    -- WHAT THE FACTION",
     b"        local r = GGUI.selected_region()\r\n        if r then return r end\r\n        return nil\r\n    end\r\n    -- WHAT THE FACTION"),
    ("a new campaign's first draw leaving out the original 18", M,
     b"                if #fresh == 0 or first then fresh = pool end",
     b"                if #fresh == 0 then fresh = pool end"),
    ("an old save's cards all changing at the next turn start", M,
     b"    if first and turn > 1 then",
     b"    if false then"),
    ("a new campaign never drawing", M,
     b"    if first and turn > 1 then",
     b"    if first then"),
    ("\"New services in 1 turns\"", U,
     b"    if n == 1 then return GGUI.loc(\"next_services_1\") end",
     b"    if false then return GGUI.loc(\"next_services_1\") end"),
    ("a service's side bundle running unlit", U,
     b"    if s.kind ~= \"bundle\" and not s.with_bundle then return false end",
     b"    if s.kind ~= \"bundle\" then return false end"),
    ("a refund drawn as good news", U,
     b"        -- GG.refund_purchase: the service could not be delivered and the favour went back.\r\n        bad = true",
     b"        -- GG.refund_purchase: the service could not be delivered and the favour went back."),
    # RACE MECHANICS, stage 2 (2026-09-29).
    ("a race row drawn for another race", M,
     b"    if s.race ~= nil and (not GG.race_on() or s.race ~= GG.culture_of(faction)) then",
     b"    if s.race ~= nil and (not GG.race_on()) then"),
    ("race rows drawn with race differences off", M,
     b"    if s.race ~= nil and (not GG.race_on() or s.race ~= GG.culture_of(faction)) then",
     b"    if s.race ~= nil and (s.race ~= GG.culture_of(faction)) then"),
    ("a hook gone since the draw still sold", M,
     b"    if not GG.needs_ok(faction, s) then return false, \"unavailable\" end",
     b""),
    ("a pool grant without the pool", M,
     b"    if s.kind == \"resource\" and not GG.has_resource(faction, s.resource) then return false end",
     b""),
    ("no race service forced on show", M,
     b"    GG.show_race_service(faction, old, keys, pools)\n",
     b""),
    ("a demand's penalty read without the race", M,
     b"GG.penalise(faction, d.guild, GG.setting_for(faction, \"demand_penalty\") or 0)",
     b"GG.penalise(faction, d.guild, GG.setting(\"demand_penalty\") or 0)"),
    ("a record noted for a factor the route ignores", M,
     b"if route and GG.pool_route_counts(route, s.factor) then",
     b"if true then"),
    ("a refused supply dilemma keeps the favour", M,
     b"if not cm:trigger_dilemma(faction, GG.SUPPLY_DILEMMAS[band]) then",
     b"if not (cm:trigger_dilemma(faction, GG.SUPPLY_DILEMMAS[band]) or true) then"),
    ("a purchase paying its own earning", M,
     b"        amount = GG.take_self(name, key, amount)\n",
     b""),
    ("last turn's record eating a real earning", M,
     b"    if r.turn ~= GG.turn_now() then return amount end\n    local left",
     b"    local left"),
    ("an earning paid to another race", M,
     b"    if GG.EARN_OF[GG.culture_of(faction) or \"\"] ~= route then return 0 end",
     b""),
    ("an earning with race differences off", M,
     b"    if not r or not faction or not GG.race_on() then return 0 end",
     b"    if not r or not faction then return 0 end"),
    ("captives from any source", M,
     b"    if route == \"captives\" then return factor == \"raiding\" or factor == \"battles\" end",
     b""),
    ("chivalry through missions counted", M,
     b"    if route == \"chivalry\" then return factor ~= \"missions\" end",
     b""),
    ("land taken from the Empire itself paid", M,
     b"    return prev_culture ~= \"wh_main_emp_empire\" and not GG.RECLAIM_SKIP[reason or \"\"]",
     b"    return not GG.RECLAIM_SKIP[reason or \"\"]"),
    ("land traded between players paid", M,
     b"                   [\"diplomacy trade\"] = true}",
     b"                   }"),
    ("land outside the old Empire paid", M,
     b"        if region:is_contained_in_region_group(GG.IMPERIAL_LANDS[i]) then return true end",
     b"        return true"),
    ("a remainder thrown away", M,
     b"        GG.earn_carry[k] = have - n * r.per",
     b"        GG.earn_carry[k] = 0"),
    ("a Log line for nothing paid", M,
     b"    if paid > 0 then GG.log_add(faction, \"earn\", r.guild, route, paid) end",
     b"    GG.log_add(faction, \"earn\", r.guild, route, paid)"),
    ("the twists ignored", M,
     b"    local p = GG.twist(faction, key)\n    if type(v)",
     b"    local p = 100\n    if type(v)"),
    ("a rule switched on rounded to off", M,
     b"    local n = math.floor(v * p / 100)\n    if n < 1 then n = 1 end",
     b"    local n = math.floor(v * p / 100)"),
    ("a rule switched off switched back on", M,
     b"    if type(v) ~= \"number\" or v <= 0 or p == 100 then return v end",
     b"    if type(v) ~= \"number\" or p == 100 then return v end"),
    ("twists with race differences off", M,
     b"    if not faction or not GG.race_on() then return 100 end",
     b"    if not faction then return 100 end"),
    ("rivalry read without the race", M,
     b"function GG.rival_loss(amount, faction)\n    local share = GG.setting_for(faction, \"rate_rivalry\")",
     b"function GG.rival_loss(amount, faction)\n    local share = GG.setting(\"rate_rivalry\")"),
    ("upkeep read without the race", M,
     b"    local share = GG.setting_for(faction, \"rate_decay\")",
     b"    local share = GG.setting(\"rate_decay\")"),
    ("a demand's timing read without the race", M,
     b"    local every = GG.setting_for(faction, \"demand_every\") or 0",
     b"    local every = GG.setting(\"demand_every\") or 0"),
    ("the favour cap without the race", M,
     b"    cap = math.floor(cap * GG.twist(faction, \"favour_cap\") / 100)\n",
     b""),
    ("a hostile service's price without the race", M,
     b"              and GG.twist(faction, \"hostile_price\") or 100",
     b"              and 100 or 100"),
    ("a failed bounty read without the race", M,
     b"    local share = GG.setting_for(faction, \"rate_bounty_fail\")",
     b"    local share = GG.setting(\"rate_bounty_fail\")"),
    ("a blessed army blessed again", M,
     b"    return not Has_Blessing_Already(mf:command_queue_index())\n       and not mf:has_effect_bundle(\"wh_dlc07_blessing_of_the_lady\")",
     b"    return true"),
    ("the Reckoning below the top level", M,
     b"    return grudge_cycle:get_current_grudge_level(faction) == 5",
     b"    return grudge_cycle:get_current_grudge_level(faction) >= 1"),
    ("the Reckoning on a rival's card", M,
     b"    if not GG.is_human(faction) then return false end\n    if cm:get_factions_bonus_value",
     b"    if cm:get_factions_bonus_value"),
    ("the blunderbusses' message by CA's broken key", M,
     b"cm:trigger_incident(faction, GG.HELLFORGE_INCIDENT_FIX[rk]",
     b"cm:trigger_incident(faction, nil"),
    ("the Muster on a full army", M,
     b"            if s.kind ~= \"unit\" and not s.room then return true end",
     b"            if s.kind ~= \"unit\" then return true end"),
    ("a race army service aimed like no character", M,
     b"GG.CHAR_KINDS = {unit = true, army = true, ranks = true, race_army = true}",
     b"GG.CHAR_KINDS = {unit = true, army = true, ranks = true}"),
    ("the court that is ahead", M,
     b"    return orth < ice and \"orthodoxy\" or \"ice_court\"",
     b"    return orth > ice and \"orthodoxy\" or \"ice_court\""),
    ("cargo on a caravan coming home", M,
     b"        if not c:is_returning() then out[#out + 1] = c end",
     b"        out[#out + 1] = c"),
    ("the Supply Train for a rival", M,
     b"    return faction == GG.WULFHART and GG.is_human(faction)",
     b"    return faction == GG.WULFHART"),
    ("the most loyal Elector favoured", M,
     b"    for band = 0, 9 do",
     b"    for band = 9, 0, -1 do"),
    ("loyalty bought for the faction leader", M,
     b"GG.RACE_TARGET_OK.bought_loyalty = function(_faction, c) return not c:is_faction_leader() end",
     b"GG.RACE_TARGET_OK.bought_loyalty = function(_faction, c) return true end"),
    ("Devotion for a Kislev faction without it", M,
     b"               and GG.has_resource(faction, \"wh3_main_ksl_devotion\") then",
     b"               then"),
    ("a tithe paid by a culture cache never filled", M,
     b"    if GG.CULTURE_OF[faction] == nil then GG.covered(faction) end\n    return (GG.CULTURE_OF[faction] or GG.CHD_CULTURE)",
     b"    return (GG.CULTURE_OF[faction] or GG.CHD_CULTURE)"),
    ("an earning filed outside Yours", U,
     b"rotation = true, earn = true},",
     b"rotation = true},"),
    ("a race card with no label", U,
     b"    if s.race then\r\n        body = \"[[col:yellow]]\"",
     b"    if false then\r\n        body = \"[[col:yellow]]\""),
    # ---- LOGIC AUDIT (2026-09-29): every guard the fix pass added.
    ("a load that leaves the patron unread until its owner's turn", M,
     b"        GG.load_patron(f)\n", b""),
    ("a load that leaves the demand unread", M,
     b"        GG.load_demand(f)\n    end", b"    end"),
    ("a load that leaves a human's research subject unread", M,
     b"        GG.load_research(h)\n", b""),
    ("a load that leaves a human's bounty board unread", M,
     b"        GG.load_bounties(h)\n    end\n    GG.load_world()", b"    end\n    GG.load_world()"),
    ("a load that leaves the world record unread", M,
     b"    GG.load_world()\nend", b"end"),
    ("the first tick not restoring the records", M,
     b"    GG.load_all()\n    GG.register()", b"    GG.register()"),
    ("a new campaign's first cards left to turn 2", M,
     b"    GG.first_cards()\nend)", b"end)"),
    ("first cards drawn again on every load", M,
     b"    if not okn or not new then return end", b"    if not okn then return end"),
    ("another faction's lord made the patron", M,
     b"        if faction and c:faction():name() ~= faction then return nil end\n", b""),
    ("a vacated post leaving its bundle on the old army", M,
     b"        if GG.patron_forces[faction] then\n"
     b"            cm:remove_effect_bundle_from_force(GG.PATRON_BUNDLE, GG.patron_forces[faction])\n"
     b"        end\n        GG.patrons[faction] = nil",
     b"        GG.patrons[faction] = nil"),
    ("the patron's army not saved with the post", M,
     b'p and (p.guild .. "," .. p.cqi .. "," .. (force or "")) or ""',
     b'p and (p.guild .. "," .. p.cqi) or ""'),
    ("an old patron save left with no army", M,
     b"        GG.patron_forces[faction] = tonumber(force) or GG.force_cqi_of(tonumber(cqi))",
     b"        GG.patron_forces[faction] = tonumber(force)"),
    ("a held lead handed to the rival after a load", M,
     b"    if held == nil then\n        local key = GG.lead_key(guild, culture)",
     b"    if false then\n        local key = GG.lead_key(guild, culture)"),
    ("the favour cap taking favour already held", M,
     b"    if g.fav < cap then g.fav = math.min(g.fav + amount, cap) end",
     b"    g.fav = math.min(g.fav + amount, cap)"),
    ("a turn's earnings not saved", M,
     b"        GG.turn_gain[faction][guild] = so_far + amount\n        GG.save_gain(faction)\n",
     b"        GG.turn_gain[faction][guild] = so_far + amount\n"),
    ("a turn's earnings not read back after a load", M,
     b"        if not GG.turn_gain[faction] then GG.turn_gain[faction] = GG.load_gain(faction) end",
     b"        if not GG.turn_gain[faction] then GG.turn_gain[faction] = {} end"),
    ("last turn's saved earnings kept at a turn start", M,
     b'    if packed and packed ~= "" then cm:set_saved_value(gain_key(faction), "") end\n',
     b""),
    ("a race earning's remainder lost on a load", M,
     b"            GG.earn_carry[k] = tonumber(cm:get_saved_value(sk)) or 0",
     b"            GG.earn_carry[k] = 0"),
    ("a gain counted across a change of hands", M,
     b"            GG.world.gain[g] = (not first and not GG.world.moved[g])",
     b"            GG.world.gain[g] = (not first)"),
    ("the roster kept for the whole session", M,
     b"    if GG.roster_cache and GG.roster_turn == GG.turn_now() then return GG.roster_cache end",
     b"    if GG.roster_cache then return GG.roster_cache end"),
    ("one battle paid once per character in it", M,
     b"            if GG.battle_paid[name] == key then return end\n", b""),
    ("grudges paid per change, not per point", M,
     b'    grudges    = {guild = "immortals",    per = 5},',
     b'    grudges    = {guild = "immortals",    rep = 10},'),
    ("a lapsed lead announced as taken by a rival", M,
     b'            if stem == "lost" and not who then return end\n', b""),
    ("the dump button heard by nothing", M,
     b'core:add_listener("gg_dump", "DerpyGGDumpStandings"',
     b'core:add_listener("gg_dump", "DerpyGGDumpStanding"'),
    ("the Reckoning sold before any grudge cycle ran", M,
     b"    if (grudge_cycle.faction_times[faction] or 0) <= 1 then return false end\n", b""),
    ("Labour Gangs sold with no labour to add to", M,
     b"GG.RACE_NEEDS.labour_gangs = function(faction)",
     b"GG.RACE_NEEDS.labour_gangs_off = function(faction)"),
    ("the Ziggurat's first upgrade taken, whatever its branch", M,
     b'                            if string.gsub(ups[j], "_%d+$", "") == stem then',
     b"                            if true then"),
    ("an upgrade the engine refused kept the favour", M,
     b"            if now ~= target.building then\n", b"            if false then\n"),
    ("a second Appoint dismissing the patron", M,
     b"        if not (p and p.guild == guild and p.cqi == cqi) then\n"
     b"            GG.set_patron(faction, guild, cqi)\n        end",
     b"        if p and p.guild == guild then GG.clear_patron(faction) else\n"
     b"            GG.set_patron(faction, guild, cqi)\n        end"),
    ("Take naming a board position", M,
     b"    local _, n = GG.bounty_for_guild(faction, arg)",
     b"    local n = tonumber(arg)"),
    ("the AI sweep guard read as 0 after a load", A,
     b'        GGAI.last_turn = tonumber(cm:get_saved_value("derpy_gg_ai_turn")) or 0',
     b"        GGAI.last_turn = 0"),
    ("the AI sweep guard never saved", A,
     b'    cm:set_saved_value("derpy_gg_ai_turn", turn)\r\n', b""),
    ("an uncovered faction given a demand and a patron", A,
     b"    -- climbed for ever (logic audit, 2026-09-29).\r\n"
     b"    if not GG.covered(faction) then return false end\r\n",
     b"    -- climbed for ever (logic audit, 2026-09-29).\r\n"),
    ("a service spent on a dead enemy or the rebels", A,
     b'                    if e:is_dead() or e:name() == "rebels" then return end',
     b"                    if false then return end"),
    ("a settlement service aimed at an enemy with no settlement", A,
     b"                    if need_regions and e:region_list():num_items() == 0 then return end\r\n",
     b""),
    ("the standings frozen with the AI switched off", A,
     b"        GG.snapshot_world(turn, 0, 0, 0)\r\n", b""),
    ("the patron pick ended on any selected lord", U,
     b"    if cqi and GG.force_cqi_of(cqi, faction) then return cqi end",
     b"    if cqi then return cqi end"),
    ("a demand's due turn shown as none left", U,
     b"    local left = (d.due or 0) - turn + 1", b"    local left = (d.due or 0) - turn"),
    ("Take sending no guild", U,
     b"        GGUI.BOUNTY_GUILD[i] = o and o.guild\r\n", b""),
    ("a held lead left unexplained", U,
     b'    if top and who and top ~= who then return "lead_held" end',
     b'    if false then return "lead_held" end'),
    ("Bought Loyalty's rule not said", U,
     b'    if s.key == "bought_loyalty" then return "needs_army_not_leader" end\r\n', b""),
    ("the footer showing the ground guild's favour off another guild", U,
     b"    local shown_fav = select(2, GG.get(faction, GGUI.ground_guild()))",
     b"    local shown_fav = fav"),
    ("upkeep promised to begin on a turn already past", U,
     b"    elseif not GG.decay_due(turn) then", b"    else"),
    ("a lapsed lead in the Log naming nobody", U,
     b'        if e.a == "" then\r\n            body = GGUI.loc("log_lead_lapsed")',
     b'        if false then\r\n            body = GGUI.loc("log_lead_lapsed")'),
    ("a Confirm kept across a selection change", U,
     b"        GGUI.CONFIRM = nil\r\n        cm:callback(function() GGUI.refresh() end, 0.1)",
     b"        cm:callback(function() GGUI.refresh() end, 0.1)"),
    # ---- the HUD hub -------------------------------------------------------
    ("the guilds button placed by itself while the hub manages it", U,
     b"    if GGUI.hubbed() then\r\n        GGUI.paint_opener(b)",
     b"    if false then\r\n        GGUI.paint_opener(b)"),
    ("the follow poll moving a button the hub manages", U,
     b"    if GGUI.hubbed() then return end            -- the hub owns its place",
     b"    -- the hub owns its place"),
    ("the hub told the guilds button is live while it is grey", U,
     b"    GGUI.opener_live = on and true or false     -- what the hub's live() reads",
     b"    GGUI.opener_live = true"),
    # 2026-10-04 polish: the header split, the text fields, the lock tag and turns in words.
    ("the guild's name left in the header's figures", U,
     b"        local line = GGUI.loc_rank(rank) .. \"   \"",
     b"        local line = GGUI.loc_guild(guild) .. \"   \" .. GGUI.loc_rank(rank) .. \"   \""),
    ("the Help and Log text field shown on every tab", U,
     b"                           gg_back_text = GGUI.TAB == 5 or GGUI.TAB == 6}) do",
     b"                           gg_back_text = true}) do"),
    ("a locked service tagged in red without the padlock", U,
     b"    return \"  [[img:\" .. GGUI.LOCK_ICON .. \"]][[/img]]\" .. text",
     b"    return \"  [[col:red]]\" .. text .. \"[[/col]]\""),
    ("a cooldown written as 7t", U,
     b"        label = label .. \"  \" .. GG.cooldown_left(faction, s.key) .. \" \"",
     b"        label = label .. \"  \" .. GG.cooldown_left(faction, s.key) .. \"t\" .. \"\""),
]


def run():
    for h in HARNESSES:
        p = subprocess.run([LUA, h], capture_output=True, cwd=ROOT)
        # stderr only: the bounty harness prints a line per passing block to stdout,
        # and the first line of the ERROR test below must be the error itself.
        if p.returncode != 0:
            return p.returncode, p.stderr.decode("utf-8", "replace")
    return 0, ""


def check(mutants, quiet=False):
    code, text = run()
    if code != 0:
        return [("the harnesses", "not green before anything was broken: " + text[-300:])]
    bad = []
    for what, path, old, new in mutants:
        src = open(path, "rb").read()
        if src.count(old) != 1:
            bad.append((what, "STALE ANCHOR - matched %d times, not 1" % src.count(old)))
            continue
        try:
            open(path, "wb").write(src.replace(old, new))
            code, text = run()
        finally:
            open(path, "wb").write(src)
        if code == 0:
            bad.append((what, "SURVIVED - both harnesses are green with this broken"))
        # The FIRST line names who raised it. The traceback under it always mentions
        # the harness (it dofiles the model), so matching the whole text catches a
        # parse error as if it were an assertion.
        elif "_harness.lua:" not in text.strip().splitlines()[0]:
            bad.append((what, "ERROR - failed without a harness assertion: " + text[-200:]))
        elif not quiet:
            print("caught: " + what)
    if run()[0] != 0:
        bad.append(("the tree", "left BROKEN - a restore did not take"))
    return bad


def selftest():
    before = open(M, "rb").read()
    harmless = [("a comment nobody can test", M, b"function GG.bounty_stake(rep)",
                 b"-- selftest\nfunction GG.bounty_stake(rep)")]
    bad = check(harmless, quiet=True)
    assert len(bad) == 1 and "SURVIVED" in bad[0][1], bad
    bad = check([("a moved anchor", M, b"no such code anywhere", b"x")], quiet=True)
    assert len(bad) == 1 and "STALE" in bad[0][1], bad
    bad = check([("a parse error", M, b"function GG.bounty_stake(rep)",
                  b"function GG.bounty_stake(")], quiet=True)
    assert len(bad) == 1 and "ERROR" in bad[0][1], bad
    assert open(M, "rb").read() == before, "the selftest did not restore the model"
    for what, path, old, _new in MUTANTS:
        n = open(path, "rb").read().count(old)
        assert n == 1, "%s: anchor matches %d times" % (what, n)
    print("selftest ok: %d mutants anchored" % len(MUTANTS))


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        selftest()
        sys.exit(0)
    bad = check(MUTANTS)
    for what, why in bad:
        print("PROBLEM: %s: %s" % (what, why))
    sys.exit(1 if bad else 0)
